# GPT-2 pretraining setup
{
  # parallelism settings ( you will want to change these based on your cluster setup, ideally scheduling pipeline stages
  # across the node boundaries )
  "pipe_parallel_size": 0,
  "model_parallel_size": 1,

  "seed": 42,

  #Tokenizer
  "make_vocab_size_divisible_by": 1,
  "tokenizer_type": "GPT2BPETokenizer",
  "data_path": "/scratch/project_462000353/HPLT-REGISTERS/samples-150B-by-register-xlmrl/tokenized/{{REGISTER}}/eng_Latn_text_document",
  "vocab_file": "/scratch/project_462000353/tokenizers/gpt2/vocab.json",
  "merge_file": "/scratch/project_462000353/tokenizers/gpt2/merges.txt",

  # model settings
  "num_layers": 24,
  "hidden_size": 2048,
  "num_attention_heads": 32,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-05,
  "pos_emb": "rotary",
  "intermediate_size": 8192,
  "no_weight_tying": true,
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",
  "num_kv_heads": 32,

  "scaled_upper_triang_masked_softmax_fusion": false,
  "bias_gelu_fusion": false,
  "use_bias_in_norms": false,
  "use_bias_in_attn_linear": false,
  "mlp_type": llama,
  "activation": "silu",

  #flash_attention - value = num_layers
  "attention_config": [[["flash"], 24]],

  # init methods
  "init_method": "small_init",
  "init_method_std": 0.02,
  "output_layer_init_method": "wang_init",

  # optimizer settings
  "optimizer":
    {
      "type": "Adam",
      "params": { "lr": 3.0e-4, "betas": [0.9, 0.95], "eps": 1.0e-8 },
    },
  "min_lr": 3.0e-5,

  # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
  "zero_optimization":
    {
      "stage": 0,
      "allgather_partitions": True,
      "allgather_bucket_size": 50000000,
      "overlap_comm": True,
      "reduce_scatter": false,
      "reduce_bucket_size": 50000000,
      "contiguous_gradients": True,
    },

  # batch / data settings
  "train_micro_batch_size_per_gpu": 4,
  "gradient_accumulation_steps": 4,
  "data_impl": "mmap",

  # regularization
  "gradient_clipping": 1.0,
  "weight_decay": 0.1,
  "hidden_dropout": 0.0,
  "attention_dropout": 0.0,

  # precision settings
  "precision": "bfloat16",
  "fp32_allreduce": true,

  # misc. training settings
  "train_iters": 166890,
  "lr_decay_iters": 100000,
  "distributed_backend": "nccl",
  "lr_decay_style": "cosine",
  "warmup": 0.01,

  #Dataloader workers
  "num_workers": 2,

  #Checkpoints HERE 10 FOR TESTING
  "checkpoint_factor": 10,
  "save": "/scratch/project_462000353/amanda/register-training/checkpoints-150B/1N/{{REGISTER}}",
  "load": "/scratch/project_462000353/amanda/register-training/checkpoints-150B/1N/{{REGISTER}}",

  # logging  HERE 1 FOR TESTING
  "log_interval": 1,
  "steps_per_print": 100,
  "tensorboard_dir": "/scratch/project_462000353/amanda/register-training/logs/tb/neox-register-150B-test-{{REGISTER}}/",
  "log_grad_pct_zeros": True,
  "log_grad_norm": True,
  "log_gradient_noise_scale": False, #Gradient Noise Scale logging does not work with zero stage 2+, as the gradients are distributed across ranks.

  #Deepspeed misc
  "wall_clock_breakdown": false,
  "tensorboard": { "enabled": false, "output_path": "logs/tb/" },
  "comms_logger":
    { "enabled": false, "verbose": false, "prof_all": true, "debug": False },
}
